export const DESC_CHANGE = "DESC_CHANGE";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const SET_PAGE = "SET_PAGE";
export const SET_SORTED_COLUMN_NAME = "SET_SORTED_COLUMN_NAME";
export const SET_FILTER_COLUMN_NAME = "SET_FILTER_COLUMN_NAME";
export const SET_FILTER_CONDITION = "SET_FILTER_CONDITION";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
